In [ ]:
# This Notebook is used for developer side EDA, it is not part of the final product

import pandas as pd
import numpy as np

In [2]:
file_path = "TXT Files/MainData.txt"

In [3]:
def read_to_df(file_path):
    df = pd.read_csv(
        file_path,
        sep=r"\|\|",
        engine="python",
        encoding="cp1252",
        dtype=str
    )

    # Clean quotes and whitespace
    df = df.apply(lambda col: col.str.strip().str.strip('"'))
    df.columns = df.columns.str.strip().str.strip('"')

    # Infer types
    df = df.apply(pd.to_numeric, errors="ignore")
    return df

In [6]:
# Read single txt file into a df
MainData = read_to_df("MainData.txt")

C:\Users\zecerman\AppData\Local\Temp\ipykernel_13880\2321772866.py:15: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors="ignore")

In [9]:
MainData.head()

   FranID  StoreID  FiscalYearID  CalendarID  AccountID       Amount
0    2526   104930          2024          10         90    7941.0376
1    2353   101215          2024           8      10320  353985.6946
2    2539   103691          2024           7         10  382601.8480
3    2075   102650          2024           1        380     406.6144
4    2691   102761          2024           5        300    2958.7837

In [11]:
MainData['FiscalYearID'].unique()

array([2024])

In [5]:
# Get all unique store ids which are not negative
df1 = MainData['StoreID']
df2 = Stores[['StoreID','StoreName']]
df3 = pd.merge(df1, df2, on="StoreID", how="left")
df3.head()

   StoreID           StoreName
0   104930   104930 - Mandrake
1   101215    101215 - Redwing
2   103691     103691 - Nelson
3   102650  102650 - Lindbergh
4   102761      102761 - Eliot

In [11]:
df = MainData['CalendarID']
df.unique()

array([10,  8,  7,  1,  5,  6, 12,  9,  4,  2,  3, 11], dtype=int64)