In [1]:
# This Notebook is used for developer side EDA, it is not part of the final product

import pandas as pd
import numpy as np

In [2]:
file_path = "TXT Files/MainData.txt"

In [3]:
def read_to_df(file_path):
    df = pd.read_csv(
        file_path,
        sep=r"\|\|",
        engine="python",
        encoding="cp1252",
        dtype=str
    )

    # Clean quotes and whitespace
    df = df.apply(lambda col: col.str.strip().str.strip('"'))
    df.columns = df.columns.str.strip().str.strip('"')

    # Infer types
    df = df.apply(pd.to_numeric, errors="ignore")
    return df

In [16]:
# Read single txt file into a df
MainData = read_to_df(file_path)

C:\Users\zecer\AppData\Local\Temp\ipykernel_24336\2321772866.py:15: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors="ignore")

In [17]:
MainData.head()

   FranID  StoreID  FiscalYearID  CalendarID  AccountID       Amount
0    2526   104930          2024          10         90    7941.0376
1    2353   101215          2024           8      10320  353985.6946
2    2539   103691          2024           7         10  382601.8480
3    2075   102650          2024           1        380     406.6144
4    2691   102761          2024           5        300    2958.7837

In [25]:
df = MainData.copy()
df = df[df['CalendarID'] == 6]
df = df[df['StoreID'] > 0]
df = df.sort_values(by='StoreID')
df['StoreID'].head(200)

1053037    100001
663432     100001
10558      100001
1290705    100001
922147     100001
            ...
55900      100008
1261968    100008
313651     100009
1727482    100009
62264      100009
Name: StoreID, Length: 200, dtype: int64

In [26]:
good_stores = df['StoreID'].unique()
bad_df = MainData[~MainData['StoreID'].isin(good_stores)]
bad_df

         FranID   StoreID  FiscalYearID  CalendarID  AccountID        Amount
13         2077 -90000814          2024           4      10100  2.716190e+06
45         2326 -90000369          2024           4        160  7.332836e+02
59         2497 -90001053          2024           5      10320 -4.682559e+04
66         2649 -90000416          2024           6        480  5.507496e+02
108        2438    101120          2024           8      10210  2.141552e+04
...         ...       ...           ...         ...        ...           ...
2300334    2612 -90000086          2024           3      10010  4.056714e+05
2300338    2326 -90000369          2024          11        190  4.377050e+03
2300363    2086 -90000987          2024          12        470  1.061872e+04
2300370    2529 -90000501          2024           8        290  1.120152e+02
2300396    2534 -90000304          2024           2        270  0.000000e+00

[134314 rows x 6 columns]

In [27]:

bad_df = bad_df[bad_df['StoreID'] > 0]
bad_df = bad_df.sort_values(by='StoreID')
bad_df

         FranID  StoreID  FiscalYearID  CalendarID  AccountID        Amount
1560147    2269   100004          2024          12        470  4.218938e+03
1725289    2269   100004          2024          12         70  8.315599e+03
1285402    2269   100004          2024          12        300  2.421318e+03
124612     2269   100004          2024          11         20  3.707066e+04
613912     2269   100004          2024          12      10140 -4.174686e+02
...         ...      ...           ...         ...        ...           ...
1059965    2181   104985          2024          12         80  4.731706e+04
283980     2181   104985          2024          12        340  1.647824e+03
1047959    2181   104985          2024          12      10230  2.323718e+06
1238548    2181   104985          2024          12        250  1.427966e+04
416066     2181   104985          2024          12      10210  2.886356e+04

[19882 rows x 6 columns]

In [28]:
bad_df['StoreID'].unique()

array([100004, 100005, 100006, 100010, 100020, 100023, 100026, 100027,
       100030, 100031, 100032, 100033, 100040, 100059, 100070, 100080,
       100101, 100111, 100112, 100113, 100152, 100213, 100261, 100262,
       100264, 100265, 100267, 100299, 100308, 100351, 100381, 100382,
       100397, 100399, 100442, 100602, 100645, 100654, 100656, 100688,
       100691, 100708, 100760, 100804, 100828, 100901, 100913, 100962,
       100985, 101004, 101055, 101056, 101095, 101113, 101114, 101120,
       101167, 101206, 101263, 101294, 101295, 101321, 101360, 101416,
       101487, 101490, 101503, 101517, 101529, 101559, 101574, 101827,
       101862, 101997, 102126, 102199, 102338, 102345, 102390, 102479,
       102481, 102485, 102560, 102574, 102590, 102749, 102788, 102800,
       102812, 102845, 102857, 102862, 102867, 102869, 102870, 102913,
       102941, 102954, 102958, 102975, 102980, 102984, 102986, 103026,
       103053, 103106, 103116, 103118, 103123, 103124, 103127, 103133,
       103169, 103217, 103329, 103345, 103409, 103549, 103753, 103942,
       103957, 103965, 103996, 104022, 104030, 104034, 104077, 104088,
       104105, 104112, 104128, 104178, 104207, 104209, 104220, 104221,
       104223, 104224, 104240, 104255, 104263, 104271, 104300, 104350,
       104351, 104381, 104385, 104395, 104520, 104522, 104699, 104759,
       104787, 104822, 104828, 104829, 104831, 104832, 104833, 104834,
       104836, 104837, 104839, 104945, 104952, 104959, 104960, 104973,
       104985], dtype=int64)